[browser]
gatherUsageStats = false

[client]
toolbarMode = "viewer"

[server]
address = "127.0.0.1"
enableCORS = true
enableXsrfProtection = true
enableStaticServing = false
headless = true
maxUploadSize = 500

[theme]
base = "dark"
primaryColor = "#22d3ee"
backgroundColor = "#020617"
secondaryBackgroundColor = "#082f49"
textColor = "#dffcff"
